# 빌드 단계
FROM debian:bullseye-slim AS build

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y \
    git \
    cmake \
    build-essential \
    maven \
    openjdk-11-jdk \
    bash

# CycloneDDS 소스 코드를 가져오고 빌드
WORKDIR /src/
RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds.git

WORKDIR /src/cyclonedds/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/dds/ ..
RUN cmake --build .
RUN cmake --build . --target install

# CycloneDDS-CXX 소스 코드를 가져오고 빌드
WORKDIR /src/
RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds-cxx.git

WORKDIR /src/cyclonedds-cxx/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/dds/ -DCMAKE_PREFIX_PATH=/dds/ ..
RUN cmake --build .
RUN cmake --build . --target install

# 런타임 단계
FROM debian:bullseye-slim

# 필요한 패키지 설치
RUN apt-get update && apt-get install -y bash cmake build-essential

# 빌드한 CycloneDDS와 CycloneDDS-CXX를 복사
WORKDIR /dds/
COPY --from=build /dds/ /dds/

# 앱 소스 코드 복사 및 빌드
COPY app/ /app
WORKDIR /app/build
RUN cmake -DCMAKE_PREFIX_PATH=/dds/ .. && cmake --build .

# 실행 명령어 설정
CMD ["./cxxRoundtripPong"]