apiVersion: crd.piccolo.org/v1alpha1
kind: VehPod
metadata:
  name: ddstest-pong
spec:
  devContainerIdx: 1
  vehContainerConfigInfo: ['dds-domain-id-a']
  vehContainerConfigIdx: 1
  appType: system
  podSpec:
    containers:
    - name: pong-container
      image: ssoonan0770/dds-test:arm_pong
    nodeSelector:
      name: "master"
